"""empty message

Revision ID: 5c04745b589e
Revises: 8f32847f3661
Create Date: 2024-06-20 09:48:25.885516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c04745b589e'
down_revision = '8f32847f3661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_creation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('product_modification_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('product_modification_date')
        batch_op.drop_column('product_creation_date')

    # ### end Alembic commands ###
