"""empty message

Revision ID: 5c135c2696e1
Revises: e4545d61c959
Create Date: 2024-06-14 12:27:45.953686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c135c2696e1'
down_revision = 'e4545d61c959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecommerce_payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('shipping_type')

    with op.batch_alter_table('ecommerce_payment', schema=None) as batch_op:
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('shipping_type')

    # ### end Alembic commands ###
