"""empty message

Revision ID: 8f32847f3661
Revises: da6b6f27044b
Create Date: 2024-06-19 12:04:10.412467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f32847f3661'
down_revision = 'da6b6f27044b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('product_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subcategory', ['subcategory_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_category_id_fkey', 'category', ['category_id'], ['id'])
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
